quarkus.hibernate-orm.log.sql=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clientesdb

# Configuración de Hibernate ORM con Panache
quarkus.hibernate-orm.database.generation=update

# Rest Client
quarkus.rest-client.rest-countries-api.url=https://restcountries.com/v3.1
quarkus.rest-client.rest-countries-api.scope=ApplicationScoped
