quarkus.hibernate-orm.log.sql=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/client-test
quarkus.datasource.username=usuario
quarkus.datasource.password=contrasena