%prod.quarkus.hibernate-orm.log.sql=true
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=admin
%prod.quarkus.datasource.jdbc.url=postgresql://postgres:5432/clientesdb

%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=admin
%dev.quarkus.datasource.jdbc.url=postgresql://postgres:5432/clientesdb

# Configuración de Hibernate ORM con Panache
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration
%prod.quarkus.hibernate-orm.sql-load-script=classpath:db/migration/v2__clients.sql

# Rest Client
quarkus.rest-client.rest-countries-api.url=https://restcountries.com/v3.1
quarkus.rest-client.rest-countries-api.scope=ApplicationScoped

# Configurar el host para permitir conexiones externas
quarkus.http.host=0.0.0.0

# Docker
quarkus.container-image.build=true
quarkus.container-image.group=quarkus
quarkus.container-image.name=client-test-jvm
quarkus.container-image.tag=latest
quarkus.jib.ports=8080

# Swagger Config
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi

%test.quarkus.datasource.devservices.enabled=true 
