ALTER TABLE clients
ALTER
COLUMN address TYPE VARCHAR(20) USING (address::VARCHAR(20));

ALTER TABLE clients
ALTER
COLUMN demonym TYPE VARCHAR(10) USING (demonym::VARCHAR(10));

ALTER TABLE clients
    ALTER COLUMN demonym SET NOT NULL;

ALTER TABLE clients
ALTER
COLUMN email TYPE VARCHAR(30) USING (email::VARCHAR(30));

ALTER TABLE clients
ALTER
COLUMN firstLastName TYPE VARCHAR(10) USING (firstLastName::VARCHAR(10));

ALTER TABLE clients
ALTER
COLUMN firstName TYPE VARCHAR(15) USING (firstName::VARCHAR(15));

ALTER TABLE clients
ALTER
COLUMN middleName TYPE VARCHAR(10) USING (middleName::VARCHAR(10));

ALTER TABLE clients
ALTER
COLUMN secondLastName TYPE VARCHAR(10) USING (secondLastName::VARCHAR(10));