name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout gh-repo
        uses: actions/checkout@v3

      - name: ☕️ Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21  
          distribution: temurin
          cache: maven

      - name: 🔧 Set execution permission for mvnw
        run: chmod +x mvnw  

      - name: 🏗️ Build with Maven
        run: ./mvnw clean package -B -DskipTests

      - name: 🐳 Build Docker image
        run: docker build -t client-test:latest .
        
      - name: 📝 List Docker images
        run: docker image ls
